# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17bb5498af3c78f542326601a4e3bc9d50bcc41cbf90dbddef4efc18cf0dedc8c0129f320a7b6250162af2f01a818f1ac9fc3c689af272d19cf50abb193d9259

test:
  secret_key_base: b11f25c403e4936b142b60f4d540161958d982f1195c64880a8d43d0ed88a249582cea659e1a050c049881219dc547ea95554d93e27a5227eb1f15baba2615a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
